Improve the generated template README
openvex/vexctl pull request #224
Opened 2024-07-11 18:41 UTC by macedogm

Small suggestion to improve the generated template README with:

1. Update the example command.
2. The status referenced `fixed`, but the text `under investigation`.
3. Some formatting improvements.
4. Typo fixes.

### Before

![image](https://github.com/openvex/vexctl/assets/17654553/5785aa65-1819-4549-b1e0-858e3c37a719)

### After

![image](https://github.com/openvex/vexctl/assets/17654553/f71e4ac2-ad76-4e3f-8cb4-015068f46d8b)

2024-07-12 09:02 UTC, cpanato approved these changes
lgtm

thanks

2024-07-12 09:03 UTC, cpanato requested changes

2024-07-12 09:03 UTC, cpanato commented on pkg/ctl/implementation.go
> +		"download [vexctl] and append new statements using\n" +
ah sorry

i think you can keep the link

```suggestion
		"download [vexctl](https://github.com/openvex/vexctl) and append new statements using\n" +
```

2024-07-12 20:51 UTC, macedogm commented on pkg/ctl/implementation.go
> +		"download [vexctl] and append new statements using\n" +
The auto generated template will be like this, because it uses the [shortcut reference link](https://github.github.com/gfm/#shortcut-reference-link).

---
# OpenVEX Templates Directory

This directory contains the OpenVEX data for this repository.
The files stored in this directory are used as templates by
`vexctl generate` when generating VEX data for a release or
a specific artifact.

To add new statements to publish data about a vulnerability,
download [vexctl] and append new statements using
`vexctl add`. For example:

```
vexctl add --in-place main.openvex.json --product pkg:oci/test --vuln CVE-2014-1234567 --status under_investigation
```

That will add a new VEX statement expressing that the impact of
CVE-2014-1234567 is under investigation in the test image. When
cutting a new release, for `pkg:oci/test` the new file can be
incorporated to the release's VEX data.

## Read more about OpenVEX

To know more about generating, publishing and using VEX data
in your project, please check out the [vexctl repository and
documentation][vexctl].

OpenVEX also has an [examples repository] with samples and docs.


[vexctl]: https://github.com/openvex/vexctl
[examples repository]: https://github.com/openvex/examples

---

We use the same shortcut in both references to `vexctl`, because the original target link is the same.

![image](https://github.com/user-attachments/assets/1866a274-6204-4894-9238-782b4fd55f97)

2024-07-15 22:41 UTC, puerco approved these changes

2024-07-16 07:56 UTC, cpanato commented
thanks

2024-07-16 07:56 UTC, merged